version: '${DOCKER_COMPOSE_VERSION}'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    command: sh -c "poetry run uvicorn src.main:app --host ${APP_HOST} --port ${APP_PORT} --workers ${APP_WORKERS}"
    ports:
      - '${APP_PORT}:8000'
    depends_on:
      clickhouse:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "if curl -s -o /dev/null -w '%{http_code}' http://${APP_HOST}:${APP_CLIENT_PORT} | grep -q 200; then echo 0; else echo 1; fi" ]
      interval: 1s
      timeout: 3s
      retries: 30

  clickhouse:
    image: clickhouse/clickhouse-server:${CLICKHOUSE_VERSION}
    container_name: clickhouse
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./clickhouse/migrations:/docker-entrypoint-initdb.d:ro
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - '${CLICKHOUSE_SERVER_PORT}:8123'
      - '${CLICKHOUSE_CLIENT_PORT}:9000'
    healthcheck:
      test: [ "CMD-SHELL", "if curl -s -o /dev/null -w '%{http_code}' http://${CLICKHOUSE_HOST}:${CLICKHOUSE_CLIENT_PORT} | grep -q 200; then echo 0; else echo 1; fi" ]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  clickhouse_data:
